AllCops:
  Exclude:
  - db/**/*

Metrics/LineLength:
  Exclude:
  - bin/**/*
  - config/**/*
  - spec/rails_helper.rb
  - spec/spec_helper.rb
  - spec/controllers/backoffice/v1/*
  - spec/controllers/api/v1/*
  - spec/support/auth_helper.rb
  - app/services/api/v1/recipes_service.rb

Style/MixinUsage:
  Exclude:
  - bin/**/*

Metrics/BlockLength:
  Exclude:
  - spec/controllers/backoffice/v1/*
  - spec/controllers/api/v1/*